name: onion_flutter
publish_to: "none"
description: All in Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 国际化包括了多种语言本地化接口的实现
  flutter_localizations:
    sdk: flutter
  # 简单的基于 json 文件的 Flutter 存储: https://pub.dev/packages/localstorage
  localstorage: 4.0.0+1
  # 提供国际化和本地化功能，包括消息翻译、复数和性别、日期/数字格式和解析以及双向文本 : https://pub.dev/packages/intl
  intl: 0.17.0
  # 简化数据结构表达: https://pub.flutter-io.cn/packages/tuple/install
  tuple: 2.0.0
  # 状态管理: https://pub.flutter-io.cn/packages/tuple/install
  provider: 6.0.2
  # 依赖注入: https://blog.csdn.net/unicorn97/article/details/100769418
  get_it: 7.2.0
  # 获取设备区域设置数据，独立于应用区域设置: https://pub.dev/packages/devicelocale
  devicelocale: 0.5.2
  # 用于查找文件系统上常用的位置: https://pub.dev/packages/path_provider
  path_provider: 2.0.10
  # 键值对存储 : https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.5
  # UI资源
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
