name: flutter_show
publish_to: "none"
description: All in Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 国际化包括了多种语言本地化接口的实现
  flutter_localizations:
    sdk: flutter

  # Base,
  url_launcher: 6.1.5 #用于在移动平台中启动URL的Flutter插件
  localstorage: 4.0.0+1 #简单的基于 json 文件的 Flutter 存储: https://pub.dev/packages/localstorage
  intl: 0.17.0 #提供国际化和本地化功能，包括消息翻译、复数和性别、日期/数字格式和解析以及双向文本 : https://pub.dev/packages/intl
  tuple: 2.0.0 #简化数据结构表达: https://pub.flutter-io.cn/packages/tuple/install
  provider: 6.0.2 #状态管理: https://pub.flutter-io.cn/packages/tuple/install
  get_it: 7.2.0 #依赖注入: https://blog.csdn.net/unicorn97/article/details/100769418
  devicelocale: 0.5.2 #获取设备区域设置数据，独立于应用区域设置: https://pub.dev/packages/devicelocale
  path_provider: 2.0.10 #用于查找文件系统上常用的位置: https://pub.dev/packages/path_provider
  shared_preferences: ^2.0.5 #键值对存储 : https://pub.dev/packages/shared_preferences
  collection: 1.16.0 # 集合操作扩展库


  # PERMISSION
  # Don't upgrade permission_handler to 10+ version. file_picker is not ready for Android 13.
  permission_handler: 9.2.0

  # HTML render
  flutter_widget_from_html_core: 0.8.5+3
  fwfh_svg: 0.7.2
  fwfh_cached_network_image: 0.7.0+2
  fwfh_url_launcher: 0.6.1+3
  fwfh_chewie: 0.7.0+1

  fwfh_webview:
    git:
      url: https://github.com/inspireui/flutter_widget_from_html.git
      ref: 1f471412850b2c5e558273e8e9a7900b389cf4a6
      path: packages/fwfh_webview

  # UI
  inspireui: 1.1.7
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  flutter_svg: 1.1.2
  extended_image: 6.2.1
  intro_slider: 3.0.9
  lottie: 1.4.0
  rive: 0.9.1
  flutter_spinkit: 5.1.0 # Loading
  flutter_zoom_drawer: 3.0.3 #颤动缩放抽屉 Flutter套件,具有侧边菜单(抽屉)的自定义实现
  flare_flutter:
    git:
      url: https://github.com/inspireui/Flare-Flutter.git
      ref: fd4bcba22aae4c028286e453deeb78f3311e689a
      path: flare_flutter


  # Tools
  universal_platform: 1.0.0+1 #判断系统平台

  # WEB TOOLS
  html_unescape: 2.0.0
  webview_flutter: 3.0.4
  webview_flutter_web: 0.1.0+4
  flutter_inappwebview: 5.4.3+7


  # Responsive UI
  responsive_builder: ^0.4.3 #Flutter之响应式UI和适配iPad方案 https://www.jianshu.com/p/4ecdbacc454d
  intl_utils: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/states/
    - lib/config/stories/
    - assets/images/
    - assets/images/country/
    - google_fonts/
### Uncomment to use custom font
#  fonts:
#    - family: Metropolis
#      fonts:
#      - asset: google_fonts/Raleway-Regular.ttf


flutter_intl:
  enabled: true


dev_dependencies:
  # 单元测试集成方式
  flutter_test:
    sdk: flutter
